version: '3.3'
services:
  auth:
    # command: gunicorn -w 4 -b 0.0.0.0:5000 "wsgi:app"
    command: flask run --host=0.0.0.0 --debug
    build: ./auth
    ports:
      - "5000:5000"
    volumes:
      - ./auth:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
